services:
  backend:
    platform: linux/amd64
    # construit un image à partir du fichier /back
    image: ecovoitwild/back-ecovoit:latest
    # build: ./back

    # A gauche le port en local, à droite celui dans docker
    ports:
      - 4000:4000
    # 'depends-on' > dit qu'un service dépend d'un autre
    env_file:
      - back/.env
      - ./secret.env
    command: sh -c "npm run build && npm run startprod"
    depends_on:
      # Nom du service du quel backend dépend
      db:
        # La db doit avoir été démarrer et etre considérée comme healthy (voir health check dans db service)
        condition: service_healthy
    environment:
      - CLIENT_URL="https://preprod.0923-jaune-1.wns.wilders.dev/graphq"

  db:
    # on utilise l'image officiel de postgres
    image: postgres:15
    # permet à la db de redémarrer en cas d'erreur/pb
    restart: always
    # "healthcheck" exécute des tests et renvoie l'état de santé de la DB (boolean).
    healthcheck:
      # les commandes à executer pour run le health check.
      test: ["CMD-SHELL", "pg_isready -d ecovoit -U ecovoit_user"]
      # le temps entre chaque execution du health check
      interval: 5s
      # Le temps max que doit prendre l'execution du health check
      timeout: 5s
      # Le nombre max d'essai consécutif. Après ça, le container est considéré comme unhealthy
      retries: 10
    env_file:
      - back/.env
    ports:
      - 5433:5432
    volumes:
      - ecovoit-data:/var/lib/postgresql/data

  db_test:
    # on utilise l'image officiel de postgres
    image: postgres:15
    # permet à la db de redémarrer en cas d'erreur/pb
    restart: always
    # "healthcheck" exécute des tests et renvoie l'état de santé de la DB (boolean).
    healthcheck:
      # les commandes à executer pour run le health check.
      test: ["CMD-SHELL", "pg_isready -d ecovoit -U ecovoit_user"]
      # le temps entre chaque execution du health check
      interval: 5s
      # Le temps max que doit prendre l'execution du health check
      timeout: 5s
      # Le nombre max d'essai consécutif. Après ça, le container est considéré comme unhealthy
      retries: 10
    env_file:
      - back/.env
    ports:
      - 5435:5432
    volumes:
      - ecovoit-data-test:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # pgadmin:
  # image: dpage/pgadmin4

  frontend:
    platform: linux/amd64
    image: ecovoitwild/front-ecovoit:latest
    # build: ./front
    # Puisqu'avec next on est sur un server, on doit le start. On n'est pas sur un fichier static
    command: sh -c "npm run build && npm run start"
    # Pas de volume puisqu'on est sur un fichier static
    # volumes:
    #   - web-frontend-build:/build
    env_file:
      - ./secret.env
    ports:
      - 3002:3000
    environment:
      - NEXT_PUBLIC_APOLLO_CLIENT_URI="https://preprod.0923-jaune-1.wns.wilders.dev/graphql"
    # depends_on:
    #   backend:
    #     condition: service_healthy

  nginx:
    image: nginx:1.21.3
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - web-frontend-build:/web-frontend-build
      - ./logs:/var/log/nginx

volumes:
  ecovoit-data:
  ecovoit-data-test: # web-frontend-build:
