services:
  backend:
    # construit un image à partir du fichier /back
    build: ./back
    # A gauche le port en local, à droite celui dans docker
    ports:
      - 4000:4000
    # Décommenter cette ligne quand on veut lancer les tests en local
    command: sh -c "npm run start:test"
    # persist les datas en dehors du container et les partage entre local et container
    # quand on modifie le fichier /back >>> modifie aussi le container
    # a gauche > local / a droite > container
    volumes:
      - ./back/src:/app/src
    # pour les utilisateurs de windows, sinon error
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CLIENT_URL=http://localhost:3002
      - GMAIL_ADDRESS=ecovoit.wild@gmail.com
      - GMAIL_PASS=dhaq iyzm xiap odec
    # 'depends-on' > dit qu'un service dépend d'un autre
    env_file:
      - back/.env
      - ./secret.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://backend:4000/graphql?query=%7B__typename%7D -H 'Apollo-Require-Preflight: true' || exit 1",
        ]
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      # Nom du service du quel backend dépend
      db:
        # La db doit avoir été démarrer et etre considérée comme healthy (voir health check dans db service)
        condition: service_healthy

  images:
    build: ./images
    ports:
      - 8000:8000
    volumes:
      - ./images/src:/app/src
      - ./images/uploads:/app/uploads

  db:
    # on utilise l'image officiel de postgres
    image: postgres:15
    # permet à la db de redémarrer en cas d'erreur/pb
    restart: always
    # "healthcheck" exécute des tests et renvoie l'état de santé de la DB (boolean).
    healthcheck:
      # les commandes à executer pour run le health check.
      test: ["CMD-SHELL", "pg_isready -d ecovoit -U ecovoit_user"]
      # le temps entre chaque execution du health chceck
      interval: 5s
      # Le temps max que doit prendre l'execution du health check
      timeout: 5s
      # Le nombre max d'essai consécutif. Après ça, le container est considéré comme unhealthy
      retries: 10
    env_file:
      - back/.env
    ports:
      - 5433:5432
    volumes:
      - ecovoit-data:/var/lib/postgresql/data

  db_test:
    # on utilise l'image officiel de postgres
    image: postgres:15
    # permet à la db de redémarrer en cas d'erreur/pb
    restart: always
    # "healthcheck" exécute des tests et renvoie l'état de santé de la DB (boolean).
    healthcheck:
      # les commandes à executer pour run le health check.
      test: ["CMD-SHELL", "pg_isready -d ecovoit -U ecovoit_user"]
      # le temps entre chaque execution du health check
      interval: 5s
      # Le temps max que doit prendre l'execution du health check
      timeout: 5s
      # Le nombre max d'essai consécutif. Après ça, le container est considéré comme unhealthy
      retries: 10
    env_file:
      - back/.env
    ports:
      - 5432:5432
    volumes:
      - ecovoit-data-test:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # pgadmin:
  # image: dpage/pgadmin4

  frontend:
    build: ./front
    env_file:
      - ./secret.env
    ports:
      - 3002:3000
    volumes:
      - ./front/src:/app/src
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_APOLLO_CLIENT_URI=http://localhost:4000
      - NEXT_PUBLIC_IMAGES_URI=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy

volumes:
  ecovoit-data:
  ecovoit-data-test:
