"use client";
/* chore */
import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";
/* Assets */
import "./globals.css";
import { gatwick, stolzl } from "./theme/ThemeOption";
import ThemeRegistery from "./theme/ThemeRegistery";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = new ApolloClient({
    uri: "http://backend:4000",
    cache: new InMemoryCache(),
    credentials: "include",
  });

  return (
    <ApolloProvider client={client}>
      <ThemeRegistery>
        <html lang="en" className={`${stolzl.variable} ${gatwick.variable}`}>
          <body className="font-stolzl">
            <main className="min-h-screen flex flex-col justify-between">
              <Header />
              {children}
              <Footer />
            </main>
          </body>
        </html>
      </ThemeRegistery>
    </ApolloProvider>
  );
}
